#!/usr/bin/bash 

WALL_DIR="$HOME/.wallpaper"

mapfile -t WALLS < <(
    ls "$WALL_DIR" \
        | sort
)

[ ${#WALLS[@]} -eq 0 ] && echo ":(" && exit 1

CURRENT_PATH=$(swww query | grep -oP 'image: \K.*')
CURRENT=$(basename "$CURRENT_PATH")
 
INDEX=-1

for i in "${!WALLS[@]}"; do
    [[ "${WALLS[$i]}" == "$CURRENT" ]] && INDEX=$i && break
done

NEXT_INDEX=$(( (INDEX + 1) % ${#WALLS[@]} ))
NEXT_WALL="${WALLS[$NEXT_INDEX]}"

matugen image "$WALL_DIR/$NEXT_WALL" > /dev/null 2>&1
