#!/usr/bin/bash

WALL_DIR="$HOME/bone/wallpapers/.wallpapers"
WALL_REPO="$HOME/bone/"

if [ ! -d $WALL_DIR ]; then
    git clone git@github.com:smol-ivan/wallpapers.git "$WALL_REPO"
fi

mapfile -t WALLS < <(
    ls "$WALL_DIR" |
        sort
)

if [ ${#WALLS[@]} -eq 0 ];then
        notify-send -u critical -i dialog-error "Error switching wallpaper"
        exit 1
fi

CURRENT_PATH=$(awww query | grep -oP 'image: \K.*')
CURRENT=$(basename "$CURRENT_PATH")

INDEX=-1

for i in "${!WALLS[@]}"; do
    [[ "${WALLS[$i]}" == "$CURRENT" ]] && INDEX=$i && break
done

NEXT_INDEX=$(((INDEX + 1) % ${#WALLS[@]}))
NEXT_WALL="${WALLS[$NEXT_INDEX]}"

matugen image "$WALL_DIR/$NEXT_WALL" --source-color-index 0 >/dev/null 2>&1

notify-send -u normal -i input-keyboard "Change wallpaper" "Imagen aplicada con exito!"

