#!/bin/bash

CONFIG="$HOME/.config/kanata/linux-symbols.kbd"
KANATA='/home/cherry/.local/bin/kanata'

pkill kanata

# Si no pones el '&', el script se queda trabado ahí y nunca llega al notify-send
pkexec bash -c "$KANATA -c $CONFIG > /dev/null 2>&1 &"

sleep 0.5

if pgrep -x "kanata" > /dev/null; then
    notify-send -u normal -i input-keyboard "Kanata" "Configuración cargada con éxito"
else
    notify-send -u critical -i dialog-error "Error en Kanata" "$ERROR"
fi
