return {
    -- "muniftanjim/prettier.nvim",
    -- config = function()
    --     require("prettier").setup({
    --         filetypes = {
    --             "css",
    --             "graphql",
    --             "html",
    --             "javascript",
    --             "javascriptreact",
    --             "json",
    --             "less",
    --             "markdown",
    --             "scss",
    --             "typescript",
    --             "typescriptreact",
    --             "yaml",
    --         },
    --     })
    -- end,
}
